### ISSUE TITLE
ParamValidationError in status-cron

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/status-api#1]
```
ERROR MESSAGE | '/aws/lambda/status-cron Parameter validation failed: Invalid type for parameter Item.availability.N, value: 100.0, type: <class 'float'>, valid types: <class 'str'>: ParamValidationError Traceback (most recent call last): File "/var/task/cron.py", line 47, in handler 'time_to_exist': {'N': str(calendar.timegm(time.gmtime()) + 180)} File "/var/task/botocore/client.py", line 320, in _api_call return self._make_api_call(operation_name, kwargs) File "/var/task/botocore/client.py", line 597, in _make_api_call api_params, operation_model, context=request_context) File "/var/task/botocore/client.py", line 633, in _convert_to_request_dict api_params, operation_model) File "/var/task/botocore/validate.py", line 291, in serialize_to_request raise ParamValidationError(report=report.generate_report()) botocore.exceptions.ParamValidationError: Parameter validation failed: Invalid type for parameter Item.availability.N, value: 100.0, type: <class 'float'>, valid types: <class 'str'> '@log_stream': 2018/11/21/[$LATEST]d30046bdc47048bd98ed343fd42f3734
-- | --
```

https://humancellatlas.airbrake.io/projects/179579/groups/2352842542780234967?tab=overview

**Comment by parthshahva** [comment]
Last seen 8 days ago with only 1 error. Closing this issue
